#!/usr/bin/env php
<?php

ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);

require './libs.php';

$config = prepare_dir_cert_files(propose_cert_files(prompt_domain()));

$v = readline(sprintf('Generate for "%s"? [y] ', $config['domain']));
if (($v === 'y') || ($v === '')) {
	generate_cert_files($config);
	echo 'ALL DONE.', PHP_EOL; }
else
	echo 'Cancelled.', PHP_EOL;
