#!/usr/bin/env php
<?php

ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);

$data = [
	'ca_cert_file' =>
	'domain' => 'example.local',
	'key_file' => 'example.local.key',
];

echo 'ALL DONE.', PHP_EOL;
