#!/usr/bin/env php
<?php

ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);

require './libs.php';

$config = propose_ca_files();

var_dump($config);

$v = readline('Generate? [y] ');
if (($v === 'y') || ($v === '')) {
	generate_ca_files($config);
	echo 'ALL DONE.', PHP_EOL; }
else
	echo 'Cancelled.', PHP_EOL;
